= Welcome to the Debezium Tutorial
:page-layout: home
:!sectids:

[.text-center.strong]
== Building Change Data Capture Pipelines

This tutorial helps you to get started with the open-source change data capture platform Debezium. You will learn about selected features and different ways, how Debezium let's you build streaming data pipelines using popular relational and non-relational databases as data sources. Examples also show, how to stream captured change events to different messaging infrastructure technologies, including but not limited to Apache Kafka.

[.tiles.browse]
== Browse modules

[.tile]
**1. Getting Started**

.xref:10-introduction.adoc[Overview]
* xref:10-introduction.adoc#cdc-concept[Change Data Capture]
* xref:10-introduction.adoc#db-support[Supported Databases]
* xref:10-introduction.adoc#deployment-modes[Deployment Modes]

[.tile]
**2. Elementary**

* xref:20-dbz-kafka-connect.adoc[Apache Kafka Connect]
* xref:21-dbz-server.adoc[Debezium Server]
* xref:22-dbz-ui.adoc[Debezium UI]

