version: '3'
services:
  kafka:
    container_name: kafka
    image: quay.io/strimzi/kafka:0.40.0-kafka-3.7.0
    command:
      - /bin/sh
      - -c
      - './bin/kafka-storage.sh format -t 9EDB9GBlQASth3IVRW0BCw -c ./config/kraft/server.properties && ./bin/kafka-server-start.sh ./config/kraft/server.properties --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS}'
    ports:
      - "9092:9092"
    environment:
      - LOG_DIR=/tmp/logs
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    networks:
      - demo-network  
  mysql:
    container_name: mysql
    image: quay.io/debezium/example-mysql:2.6
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=debezium
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysql
    networks:
      - demo-network
  connect:
    container_name: connect
    image: quay.io/debezium/connect:2.6
    ports:
      - "8083:8083"
    depends_on:
      - kafka
      - mysql
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
      - ENABLE_DEBEZIUM_KC_REST_EXTENSION=true
      - ENABLE_DEBEZIUM_SCRIPTING=true
      #- CONNECT_REST_EXTENSION_CLASSES=io.debezium.kcrestextension.DebeziumConnectRestExtension
    networks:
      - demo-network
  debezium-ui:
    container_name: debezium-ui
    #NOTE: tag '2.5' is the most recent currently but has no arm image on quay yet hence sticking to 2.2
    image: quay.io/debezium/debezium-ui:2.2
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CONNECT_URIS=http://connect:8083
    depends_on:
      - connect
    networks:
      - demo-network
networks:
  demo-network:
    name: dbz-ui